In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Sales-Export_2019-2020.csv")

In [4]:
df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2/12/2020,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,9/26/2019,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,7/11/2019,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,4/2/2020,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,12/22/2019,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   country            1000 non-null   str
 1    order_value_EUR   1000 non-null   str
 2    cost              1000 non-null   float64
 3   date               1000 non-null   str
 4   category           1000 non-null   str
 5   customer_name      1000 non-null   str
 6   sales_manager      1000 non-null   str
 7   sales_rep          1000 non-null   str
 8   device_type        1000 non-null   str
 9   order_id           1000 non-null   str
dtypes: float64(1), str(9)
memory usage: 78.3 KB

In [6]:
df.isnull().sum()

country              0
 order_value_EUR     0
 cost                0
date                 0
category             0
customer_name        0
sales_manager        0
sales_rep            0
device_type          0
order_id             0
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.fillna(0, inplace=True)

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2/12/2020,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,9/26/2019,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,7/11/2019,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,4/2/2020,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,12/22/2019,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160
...,...,...,...,...,...,...,...,...,...,...
995,France,"46,296.26",40319.41,5/15/2020,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
996,Belgium,"118,061.05",101131.10,7/2/2020,Appliances,Johns and Sons,Lambert Norheny,Collin Mackness,Mobile,59-2117058
997,Finland,"74,480.56",60023.88,3/6/2020,Clothing,Homenick-Marvin,Hube Corey,Wat Bowkley,PC,31-1849120
998,Spain,"87,205.01",69171.01,6/18/2020,Games,Johns and Sons,Emalia Dinse,Manuel Goudie,Tablet,45-3085595
999,Portugal,"107,716.72",86679.64,1/18/2020,Accessories,"Jacobson, Marvin and Brown",Celine Tumasian,Brynn Dempster,Mobile,61-3294149

In [10]:
df.fillna("Unknown", inplace=True)

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2/12/2020,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,9/26/2019,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,7/11/2019,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,4/2/2020,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,12/22/2019,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160
...,...,...,...,...,...,...,...,...,...,...
995,France,"46,296.26",40319.41,5/15/2020,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
996,Belgium,"118,061.05",101131.10,7/2/2020,Appliances,Johns and Sons,Lambert Norheny,Collin Mackness,Mobile,59-2117058
997,Finland,"74,480.56",60023.88,3/6/2020,Clothing,Homenick-Marvin,Hube Corey,Wat Bowkley,PC,31-1849120
998,Spain,"87,205.01",69171.01,6/18/2020,Games,Johns and Sons,Emalia Dinse,Manuel Goudie,Tablet,45-3085595
999,Portugal,"107,716.72",86679.64,1/18/2020,Accessories,"Jacobson, Marvin and Brown",Celine Tumasian,Brynn Dempster,Mobile,61-3294149

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")

In [14]:
df.dtypes

country                  str
_order_value_eur_        str
_cost_               float64
date                     str
category                 str
customer_name            str
sales_manager            str
sales_rep                str
device_type              str
order_id                 str
dtype: object

In [16]:
df.columns

Index(['country', '_order_value_eur_', '_cost_', 'date', 'category',
       'customer_name', 'sales_manager', 'sales_rep', 'device_type',
       'order_id'],
      dtype='str')

In [22]:
df['date'] = pd.to_datetime(df['date'])

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   country            1000 non-null   str
 1   _order_value_eur_  1000 non-null   str
 2   _cost_             1000 non-null   float64
 3   date               1000 non-null   datetime64[us]
 4   category           1000 non-null   str
 5   customer_name      1000 non-null   str
 6   sales_manager      1000 non-null   str
 7   sales_rep          1000 non-null   str
 8   device_type        1000 non-null   str
 9   order_id           1000 non-null   str
dtypes: datetime64[us](1), float64(1), str(8)
memory usage: 78.3 KB

In [24]:
df.columns

Index(['country', '_order_value_eur_', '_cost_', 'date', 'category',
       'customer_name', 'sales_manager', 'sales_rep', 'device_type',
       'order_id'],
      dtype='str')

In [25]:
df['country'] = df['country'].str.title()

In [27]:
df.columns

Index(['country', '_order_value_eur_', '_cost_', 'date', 'category',
       'customer_name', 'sales_manager', 'sales_rep', 'device_type',
       'order_id'],
      dtype='str')

In [28]:
df['country'] = df['country'].str.title()

In [29]:
df['category'] = df['category'].str.upper()

In [30]:
df['customer_name'] = df['customer_name'].str.strip()

In [31]:
df.head()

,country,_order_value_eur_,_cost_,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2020-02-12,BOOKS,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,2019-09-26,GAMES,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,2019-07-11,CLOTHING,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,2020-04-02,BEAUTY,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,2019-12-22,GAMES,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   country            1000 non-null   str
 1   _order_value_eur_  1000 non-null   str
 2   _cost_             1000 non-null   float64
 3   date               1000 non-null   datetime64[us]
 4   category           1000 non-null   str
 5   customer_name      1000 non-null   str
 6   sales_manager      1000 non-null   str
 7   sales_rep          1000 non-null   str
 8   device_type        1000 non-null   str
 9   order_id           1000 non-null   str
dtypes: datetime64[us](1), float64(1), str(8)
memory usage: 78.3 KB

In [33]:
df.head()

,country,_order_value_eur_,_cost_,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2020-02-12,BOOKS,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,2019-09-26,GAMES,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,2019-07-11,CLOTHING,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,2020-04-02,BEAUTY,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,2019-12-22,GAMES,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160

In [34]:
df.to_csv("cleaned_sales_data.csv", index=False)